name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Node App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: 🧶 Yarn
        run: yarn

      - name: 🛠 Build
        run: yarn build

      - name: RSync
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: '/dist/*'
          dest: 'jminguely@ssh-jminguely.alwaysdata.net:www/cinq.band'
